### ISSUE TITLE
Run on MacOS fatal.

### ISSUE THREAD

**Issue by leopku** [befovy/fvm#1]
After install, running `fvm install v1.9.0`

fvm: Invalid fvm home /Users/leo/Library/Application Support/fvm, magic file ".fvmhome" not exist

**Comment by befovy** [comment]
回家没带电脑，看不了了

**Comment by leopku** [comment]
手动创建这个文件解决

建议安装时自动创建

**Comment by leopku** [comment]
可以参考一下 rbenv 及其衍生的 pyenv、nodenv、goenv 等等
