### ISSUE TITLE
[question]where is my flutter?

### ISSUE THREAD

**Issue by ariagecheney** [befovy/fvm#11]
look at picture below.
0 macos 10.15.4 ,mbp 2019
1  brew install fvm
2  previous  flutter path: ~/flutter/flutter/xxxxxx ;  channel:master
3 exec fvm import ~/flutter/flutter/, wait some minutes,  
4 terrible result, my flutter is lost!!!
5 how can i  find or  rescue it?
6 in your dir:/Users/chy/Library/Application Support/fvm/versions,    no exists my flutter sdk!!!
7 please help me  , i am searching globally in mac but no result.
![flutter存储](https://user-images.githubusercontent.com/35078844/84249294-262c1780-ab3d-11ea-8044-870ea7c33aff.png)
![fvm2](https://user-images.githubusercontent.com/35078844/84249301-275d4480-ab3d-11ea-8ea7-44452966f067.png)

**Comment by befovy** [comment]
Terrible, really nothing in  `/Users/chy/Library/Application Support/fvm/` ?

**Comment by befovy** [comment]
Can't reproduce
