### ISSUE TITLE
fvm: v1.17.3 is not a valid version

### ISSUE THREAD

**Issue by 948911908** [befovy/fvm#12]
我运行 fvm install v1.17.3 命令，结果提示我v1.17.3 is not a valid version

**Comment by befovy** [comment]
fvm checks if a version is listed in the output of `flutter version`.

但是 flutter 好坑，`flutter version` 输出以前是有 v 前缀的，最近的版本怎么都没有了

**Comment by 948911908** [comment]
xhjdeMacBook-Pro:~ xhj$ flutter version
v1.12.13+hotfix.9
v1.16.3
v1.16.2
v1.16.1
v1.16.0
v1.15.22
v1.15.21
v1.15.20

运行flutter version是这样显示的 @befovy
