### ISSUE TITLE
如何彻底删除fvm

### ISSUE THREAD

**Issue by aluo44** [befovy/fvm#18]
如何彻底删除fvm
如下:
`Warning! This package referenced a Flutter repository via the .packages file that is no longer available. The repository from which the 'flutter' tool is currently executing will be used instead.
  running Flutter tool: /Users/cp/flutter
  previous reference  : /Users/cp/Library/Application Support/fvm/versions/stable
This can happen if you deleted or moved your copy of the Flutter repository, or if it was on a volume that is no longer mounted or has been mounted at a different location. Please check your system path to verify that you are
running the expected version (run 'flutter --version' to see which flutter is on your path).`

**Comment by befovy** [comment]
如何彻底删除fvm：
删除目录 /Users/cp/Library/Application Support/fvm 以及 fvm 可执行文件。

但是上面 warning 信息可不是这个意思，删除要慎重。

**Comment by aluo44** [comment]
好的,谢谢
