### ISSUE TITLE
建议：加一个检测已有SDK，并导到FVM中

### ISSUE THREAD

**Issue by JieSmart** [befovy/fvm#2]
如题。还有对已知项目的使用的SDK进行重新指向

**Comment by befovy** [comment]
> 加一个检测已有SDK，并导到FVM中

这个很赞。


但是第二句 “对已知项目的使用的SDK进行重新指向” 不太理解

**Comment by JieSmart** [comment]
> > 加一个检测现有SDK，并导到FVM中
> 
> 这个很赞。
> 
> 但是第二句“对已知项目的使用的SDK进行重新指向”

就是目前`fvm use <version> --locol`这个好像不太好使。我在Android Studio查看的时时候还是指向的是之前的路径。

**Comment by befovy** [comment]
`fvm use <version> --locol` 没有修改环境变量。
所以直接用 flutter 命令其实不会有啥变化。

`fvm use <version> --locol` 配合 `fvm  flutter doctor` `fvm flutter run` 等使用，就是要给原本的 flutter 命令加上 fvm 前缀

**Comment by RogerBu** [comment]
"检测已有SDK，并导到FVM中" +1

**Comment by befovy** [comment]
周末打算加上 “检测已有SDK，并导到FVM中” 功能，这个使用什么子命令何时呢？

**Comment by JieSmart** [comment]
> 周末打算加上 “检测已有SDK，并导到FVM中” 功能，这个使用什么子命令何时呢？

`fvm current`:如果没有选择过版本。就检测当前并使用
`fvm list`：使用这个命令时，首先检测本地是否存在
`fvm list --local` ：或者使用这个检测本地包含，通过fvm下载和本地已存在的flutter版本

**Comment by befovy** [comment]
released in 0.4.0
