### ISSUE TITLE
安装版本显示0.7 --version显示为0.6 最新为0.8怎么升级

### ISSUE THREAD

**Issue by tom0gao** [befovy/fvm#20]
使用 fvm use dev --local 无法切换 还是statble

**Comment by befovy** [comment]
brew tap befovy/taps
brew install fvm

`brew upgrade fvm` 就可以升级了呀

**Comment by befovy** [comment]
> 使用 fvm use dev --local 无法切换 还是statble

这是因为 PATH 不对。
如果要有 --local 方式使用 flutter，应该使用 proxy command

https://github.com/befovy/fvm#proxy-commands
