### ISSUE TITLE
[feature] 支持配置文件制定flutter版本和仓库地址

### ISSUE THREAD

**Issue by cikelengfeng** [befovy/fvm#22]
有时我们在一个工程的不同分支可能会使用不同的引擎版本（如适配新引擎的时候），目前的做法是切换完分支后，手动调用 fvm use xxx --local 来切换，我建议可以支持项目中定义一个fvm.properties 文件，文件中记录flutter git ref 和 flutter 仓库地址，该文件可以提交到代码仓库中，这样在切换不同分支时，fvm 命令自动根据 fvm.properties 文件中的版本切换引擎，体验会更好，并且也可以多人开发时确保使用相同的引擎。

**Comment by befovy** [comment]
这个稍微有些复杂了。这个idea 中还要每次切换分支或者进入别的项目，再运行一次 fvm 某个子命令吗

**Comment by cikelengfeng** [comment]
> 这个稍微有些复杂了。这个idea 中还要每次切换分支或者进入别的项目，再运行一次 fvm 某个子命令吗

我理解应该不用调用fvm命令。fvm.properties 的作用非常类似于 gemfile、podfile 这类文件

**Comment by befovy** [comment]
工程配置以及ide 都不理解 fvm 程序，也不理解 fvm.properties。
ide 都是直接使用 flutter 命令，如果没有任何环节去处理  fvm.properties ，怎么才能实现自动切换呢？

**Comment by cikelengfeng** [comment]
我明白你的意思了，是我上一条回复写的不对，还是需要执行任意一条fvm 命令才能够切换成 fvm.properties 文件中指定的版本

**Comment by befovy** [comment]
所以这个步骤如果不能去掉的话，这个feature 没啥意义。感谢你的 idea

**Comment by cikelengfeng** [comment]
这个功能还是有意义的，如果把fvm.properties文件提交到代码库，大家就可以很容易的同步更新引擎版本

befovy <notifications@github.com>于2020年11月21日 周六10:42写道：
