### ISSUE TITLE
linkpath方式android studio无法找到sdk

### ISSUE THREAD

**Issue by xymelon** [befovy/fvm#4]
感谢作者，很好很强大。
但是在android studio中linkpath方式无法定位sdk，如果能直接把相应版本的sdk复制过去就能完美实现。

**Comment by befovy** [comment]
因为现在 link 的是一个可执行文件。 我在增加一个文件夹 link 应该就可以了

**Comment by xymelon** [comment]
期待 如果能改好 这工具就很完美呢

**Comment by befovy** [comment]
0.5.0 版本已发布，增加了文件夹 link
