### ISSUE TITLE
如何更新flutter SDK

### ISSUE THREAD

**Issue by z234009184** [befovy/fvm#6]
比如flutter 发布稳定版本1.17.1
我通过fvm list-remote 并没有找到最新版本,无法通过fvm use来切换新版本
而是通过flutter upgrade进行更新

**Comment by befovy** [comment]
fvm 没有 list-remote 命令。

如果 `fvm current` 结果显示你当前正在用 stable 版本，并且你想把当前 stable 的 flutter 更新到新发布的的 stable 版本，你应该使用 flutter upgrade。

如果你正在用别的版本，你应该首先 `fvm use stable`，然后 `flutter upgrade`

如果你明确想安装一个新的 flutter 版本号，而不是升级已经安装的版本，你应该使用 
`fvm install v1.17.1`

**Comment by z234009184** [comment]
好的, 谢谢 答复
