### ISSUE TITLE
fatal: Invalid symlink 'C:/fvm/current': Function not implemented

### ISSUE THREAD

**Issue by xxzj990** [befovy/fvm#9]
win10 64位系统
fvm install
fvm use
完成后，运行flutter doctor报如题的错

**Comment by befovy** [comment]
你好，请问在你硬盘中 `C:/fvm/current` 文件存在吗？ 是个有效的软链接吗

**Comment by xxzj990** [comment]
> 你好，请问在你硬盘中 `C:/fvm/current` 文件存在吗？ 是个有效的软链接吗

是的，软链接看起来是正常的。下面是截图：

![微信截图_20200605153425](https://user-images.githubusercontent.com/5134154/83849583-38bfde80-a742-11ea-8b7c-e4cd43a831d6.png)

![微信截图_20200605153451](https://user-images.githubusercontent.com/5134154/83849591-3c536580-a742-11ea-8210-7da25b0a470c.png)

**Comment by xxzj990** [comment]
@befovy 我感觉是自动生成软链接时的分割符有问题。

Windows的分割符应该是这样：C:\fvm\current

但是从报错看好像给生成为了：C:/fvm/current

是不是Linux和Windows要分开处理一下？谢谢

**Comment by befovy** [comment]
运行 `flutter doctor` 的时候，这个 flutter 的路径在哪呢？ 
如果它就是软链接目录里的 flutter？ 那就很奇怪呀。

**Comment by befovy** [comment]
@xxzj990 Hi，我对此问题进行了修复，可以测试一下吗？ 使用 feature/filepath 分支，谢谢

**Comment by xxzj990** [comment]
> @xxzj990 Hi，我对此问题进行了修复，可以测试一下吗？ 使用 feature/filepath 分支，谢谢

好的，测完我会回复结果，谢谢

**Comment by xxzj990** [comment]
> @xxzj990 Hi，我对此问题进行了修复，可以测试一下吗？ 使用 feature/filepath 分支，谢谢

遇到个尴尬问题，没用过go，不知道怎么从分支安装，网上查了下尝试用：

- go get -u -v github.com/befovy/fvm@feature/filepath

不行。可以帮忙打包一个exe吗，谢谢。

**Comment by befovy** [comment]
> > @xxzj990 Hi，我对此问题进行了修复，可以测试一下吗？ 使用 feature/filepath 分支，谢谢
> 
> 遇到个尴尬问题，没用过go，不知道怎么从分支安装，网上查了下尝试用：
> 
> * go get -u -v github.com/befovy/fvm@feature/filepath
> 
> 不行。可以帮忙打包一个exe吗，谢谢。

你先 clone 下来，然后 checkout 到分支，再 go build 呢？

**Comment by xxzj990** [comment]
> > > @xxzj990 Hi，我对此问题进行了修复，可以测试一下吗？ 使用 feature/filepath 分支，谢谢
> > 
> > 
> > 遇到个尴尬问题，没用过go，不知道怎么从分支安装，网上查了下尝试用：
> > 
> > * go get -u -v github.com/befovy/fvm@feature/filepath
> > 
> > 不行。可以帮忙打包一个exe吗，谢谢。
> 
> 你先 clone 下来，然后 checkout 到分支，再 go build 呢？

build出exe了。

还是原来的报错。。。

- fatal: Invalid symlink 'C:/fvm/current': Function not implemented

**Comment by befovy** [comment]
已经下载的你删除了吗

**Comment by xxzj990** [comment]
> 已经下载的你删除了吗

我是用的之前fvm install beta获得的flutter，要完全重新下载吗，我试试吧

**Comment by xxzj990** [comment]
> 已经下载的你删除了吗

把以前的东西都删了，重新下载后还是报错，感觉没有找到问题所在。下面截图是我执行flutter doctor的输出，感觉已经链接到文件夹了，都可以执行flutter的安装，就是会报错，也会导致找不到flutter的版本号等。

![微信截图_20200609084150](https://user-images.githubusercontent.com/5134154/84093640-63a17f80-aa2d-11ea-9ab7-ec295dd45dc0.png)

**Comment by befovy** [comment]
`fvm current` 命令回打印安装 flutter 的实际位置。
直接该文件夹中的 flutter 应该可以的吧。 这样做都和 fvm 没啥关系了

**Comment by xxzj990** [comment]
> `fvm current` 命令会打印安装 flutter 的实际位置。
> 直接该文件夹中的 flutter 应该可以的吧。 这样做都和 fvm 没啥关系了

去文件夹直接运行也不行，截图如下：
![微信截图_202006100857531](https://user-images.githubusercontent.com/5134154/84215341-8ea4d580-aaf8-11ea-91ce-2b29e2652974.png)

**Comment by xxzj990** [comment]
> `fvm current` 命令会打印安装 flutter 的实际位置。
> 直接该文件夹中的 flutter 应该可以的吧。 这样做都和 fvm 没啥关系了

但是我试了一下，用如下命令可以：

- fvm flutter doctor

截图如下：
![微信截图_202006100856029](https://user-images.githubusercontent.com/5134154/84215406-b8f69300-aaf8-11ea-9e09-6a77f2028ad9.png)

**Comment by xxzj990** [comment]
顺便提一下，fvm命令在Windows自带cmd下会乱码。

![微信截图_202006100902559](https://user-images.githubusercontent.com/5134154/84215573-43d78d80-aaf9-11ea-9e3f-94b69b5f8c5e.png)

**Comment by befovy** [comment]
@xxzj990 hi 我看你截图都是直接使用的 flutter fvm 命令，这两个程序在环境变量中的位置是否正确呢？可以用windows 的 where 命令看一下

**Comment by xxzj990** [comment]
> @xxzj990 hi 我看你截图都是直接使用的 flutter fvm 命令，这两个程序在环境变量中的位置是否正确呢？可以用windows 的 where 命令看一下

见下图：
![微信截图_20200611183949](https://user-images.githubusercontent.com/5134154/84376044-05ce8c80-ac13-11ea-99a5-fb8362b7bad0.png)


环境变量是对的

**Comment by xxzj990** [comment]
暂时的解决方法就是使用如下命令打包，后面再看这个问题能不能解决吧，谢谢你的回复。

需要用到beta环境时，这样打包：

- fvm flutter build web

stable环境这样打包：

- flutter build apk
- flutter build ios
